export const MOCK_DATA = [
  {
    Publiceringsdatum: "2019-09-23",
    Utgivare: "A boring company AB",
    "Person i ledande ställning": "Sven Svensson",
    Befattning: "VD",
    Karaktär: "Förvärv",
    Instrumentnamn: "Boring company",
    ISIN: "SE3400000873",
    Transaktionsdatum: "2019-09-23",
    Volym: "1000",
    Volymsenhet: "Antal",
    Pris: "10,52",
    Valuta: "SEK",
    Handelsplats: "A place of trade",
  },
  {
    Publiceringsdatum: "2019-09-22",
    Utgivare: "A boring company AB",
    "Person i ledande ställning": "Sven Svensson",
    Befattning: "VD",
    Karaktär: "Förvärv",
    Instrumentnamn: "Boring company",
    ISIN: "SE3400000873",
    Transaktionsdatum: "2019-09-22",
    Volym: "10000",
    Volymsenhet: "Antal",
    Pris: "6,52",
    Valuta: "SEK",
    Handelsplats: "A place of trade",
  },
  {
    Publiceringsdatum: "2019-09-21",
    Utgivare: "A boring company AB",
    "Person i ledande ställning": "Sven Svensson",
    Befattning: "VD",
    Karaktär: "Förvärv",
    Instrumentnamn: "Boring company",
    ISIN: "SE3400000873",
    Transaktionsdatum: "2019-09-21",
    Volym: "1000",
    Volymsenhet: "Antal",
    Pris: "9,52",
    Valuta: "SEK",
    Handelsplats: "A place of trade",
  },
  {
    Publiceringsdatum: "2019-09-23",
    Utgivare: "A boring company AB",
    "Person i ledande ställning": "Anders Andersson",
    Befattning: "Vice VD",
    Karaktär: "Förvärv",
    Instrumentnamn: "Boring company",
    ISIN: "SE3400000873",
    Transaktionsdatum: "2019-09-23",
    Volym: "1000",
    Volymsenhet: "Antal",
    Pris: "12,52",
    Valuta: "SEK",
    Handelsplats: "A place of trade",
  },
  {
    Publiceringsdatum: "2019-09-22",
    Utgivare: "A boring company AB",
    "Person i ledande ställning": "Anders Andersson",
    Befattning: "Vice VD",
    Karaktär: "Förvärv",
    Instrumentnamn: "Boring company",
    ISIN: "SE3400000873",
    Transaktionsdatum: "2019-09-22",
    Volym: "10000",
    Volymsenhet: "Antal",
    Pris: "3,52",
    Valuta: "SEK",
    Handelsplats: "A place of trade",
  },
  {
    Publiceringsdatum: "2019-09-21",
    Utgivare: "A boring company AB",
    "Person i ledande ställning": "Anders Andersson",
    Befattning: "Vice VD",
    Karaktär: "Förvärv",
    Instrumentnamn: "Boring company",
    ISIN: "SE3400000873",
    Transaktionsdatum: "2019-09-21",
    Volym: "1000",
    Volymsenhet: "Antal",
    Pris: "6,52",
    Valuta: "SEK",
    Handelsplats: "A place of trade",
  },

  {
    Publiceringsdatum: "2019-09-23",
    Utgivare: "Wholesale AB",
    "Person i ledande ställning": "Erik Eriksson",
    Befattning: "VD",
    Karaktär: "Förvärv",
    Instrumentnamn: "Boring company",
    ISIN: "SE3400000973",
    Transaktionsdatum: "2019-09-23",
    Volym: "2000",
    Volymsenhet: "Antal",
    Pris: "10,52",
    Valuta: "SEK",
    Handelsplats: "A place of trade",
  },
  {
    Publiceringsdatum: "2019-09-22",
    Utgivare: "Wholesale AB",
    "Person i ledande ställning": "Erik Eriksson",
    Befattning: "VD",
    Karaktär: "Förvärv",
    Instrumentnamn: "Wholesale",
    ISIN: "SE3400000973",
    Transaktionsdatum: "2019-09-22",
    Volym: "20000",
    Volymsenhet: "Antal",
    Pris: "6,52",
    Valuta: "SEK",
    Handelsplats: "A place of trade",
  },
  {
    Publiceringsdatum: "2019-09-21",
    Utgivare: "Wholesale AB",
    "Person i ledande ställning": "Erik Eriksson",
    Befattning: "VD",
    Karaktär: "Förvärv",
    Instrumentnamn: "Wholesale",
    ISIN: "SE340000973",
    Transaktionsdatum: "2019-09-21",
    Volym: "2000",
    Volymsenhet: "Antal",
    Pris: "9,52",
    Valuta: "SEK",
    Handelsplats: "A place of trade",
  },
  {
    Publiceringsdatum: "2019-09-23",
    Utgivare: "Wholesale AB",
    "Person i ledande ställning": "Anders Andersson",
    Befattning: "Vice VD",
    Karaktär: "Förvärv",
    Instrumentnamn: "Boring company",
    ISIN: "SE3400000973",
    Transaktionsdatum: "2019-09-23",
    Volym: "2000",
    Volymsenhet: "Antal",
    Pris: "12,52",
    Valuta: "SEK",
    Handelsplats: "A place of trade",
  },
  {
    Publiceringsdatum: "2019-09-22",
    Utgivare: "Wholesale AB",
    "Person i ledande ställning": "Anders Andersson",
    Befattning: "Vice VD",
    Karaktär: "Förvärv",
    Instrumentnamn: "Boring company",
    ISIN: "SE3400000973",
    Transaktionsdatum: "2019-09-22",
    Volym: "20000",
    Volymsenhet: "Antal",
    Pris: "3,52",
    Valuta: "SEK",
    Handelsplats: "A place of trade",
  },
  {
    Publiceringsdatum: "2019-09-21",
    Utgivare: "Wholesale AB",
    "Person i ledande ställning": "Anders Andersson",
    Befattning: "Vice VD",
    Karaktär: "Förvärv",
    Instrumentnamn: "Boring company",
    ISIN: "SE3400000973",
    Transaktionsdatum: "2019-09-21",
    Volym: "2000",
    Volymsenhet: "Antal",
    Pris: "6,52",
    Valuta: "SEK",
    Handelsplats: "A place of trade",
  },
]
